In [1]:
import pandas as pd
import zipfile
# Mostrar todas las columnas sin l√≠mite
pd.set_option('display.max_columns', None)

In [2]:
dia_semana = 'lunes'
# Ruta al archivo zip
zip_path = f'{dia_semana}.zip'

# Abrir el zip
with zipfile.ZipFile(zip_path) as z:
    # Abrir solo el archivo CSV deseado
    with z.open('productos.csv') as f:
        productos_df = pd.read_csv(f, sep='|')

productos_df.head()

/var/folders/gf/xjt2z0l14fn8dy1y22cnhzm40000gn/T/ipykernel_49586/924793652.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  productos_df = pd.read_csv(f, sep='|')

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,10,1.0,63.0,7.790771e+12,1.0,TOALLA NOSOTRAS CLASICAS C CALENDULA X 16U,1.0,UNI,NOSOTRAS,2709.0,169.31,16.0,UNI,NaN,NaN,NaN,NaN
1,10,3.0,711.0,7.790070e+12,1.0,FIDEOS DEDALITOS LUCCHETTI BOLSA X 500 GRS,1.0,UNI,LUCCHETTI,1439.0,2878.00,500.0,GRM,NaN,NaN,NaN,NaN
2,10,1.0,44.0,7.622202e+12,1.0,GALLETITAS BOCA DE DAMA TERRABUSI X 170 GRS,1.0,UNI,TERRABUSI,995.0,5852.94,170.0,GRM,NaN,NaN,NaN,NaN
3,10,2.0,62.0,7.791293e+12,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,3969.0,15876.00,250.0,CM3,NaN,NaN,NaN,NaN
4,10,1.0,2.0,7.791720e+12,1.0,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN

In [3]:
productos_df.tail()

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
2276664,10,3.0,736.0,7.790010e+12,1.0,ACOND HIDRATACION INTENSA JOHNSONS KIDS X 200 CC,1.0,UNI,JOHNSONS BABY,4965.0,24825.0,200.0,CM3,2310.0,Promo A valida desde el 17/04/2025 hasta 20/05...,NaN,NaN
2276665,10,2.0,262.0,7.798162e+12,1.0,SAHUMERIO ILUMINARTE BANGLADESH FRUTILLA X15,1.0,UNI,ILUMINARTE,1290.0,1290.0,1.0,UNI,NaN,NaN,NaN,NaN
2276666,10,3.0,748.0,7.730908e+12,1.0,JUGO EN POLVO MIX FRUTAL RINDE DOS X 13GRS,1.0,UNI,RINDE DOS,559.0,4300.0,13.0,GRS,NaN,NaN,NaN,NaN
2276667,10,3.0,450.0,7.790070e+12,1.0,FIDEOS INTEGRALES SPAGHETTI MATARAZZO X 500 GRS,1.0,UNI,MATARAZZO,2009.0,4018.0,500.0,GRM,NaN,NaN,NaN,NaN
2276668,Ultima actualizaci√≥n: 2025-05-12T05:04:32-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Notamos que el ultimo registro de cada csv es irrelevante
productos_df = productos_df.drop(productos_df.index[-1])

In [5]:
productos_df.isnull().sum()

id_comercio                                   0
id_bandera                                    0
id_sucursal                                   0
id_producto                                   0
productos_ean                                 0
productos_descripcion                         0
productos_cantidad_presentacion               0
productos_unidad_medida_presentacion          0
productos_marca                               0
productos_precio_lista                        0
productos_precio_referencia                   0
productos_cantidad_referencia                 0
productos_unidad_medida_referencia            0
productos_precio_unitario_promo1        2214305
productos_leyenda_promo1                2214305
productos_precio_unitario_promo2        2276668
productos_leyenda_promo2                2276668
dtype: int64

In [6]:
len(productos_df)

2276668

In [7]:
productos_df.columns

Index(['id_comercio', 'id_bandera', 'id_sucursal', 'id_producto',
       'productos_ean', 'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion', 'productos_marca',
       'productos_precio_lista', 'productos_precio_referencia',
       'productos_cantidad_referencia', 'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1', 'productos_leyenda_promo1',
       'productos_precio_unitario_promo2', 'productos_leyenda_promo2'],
      dtype='object')

In [8]:
# verificamos cuantos registros tienen el codigo de producto EAN y cuantos no
productos_df['productos_ean'].value_counts()

productos_ean
1.0    2221991
0.0      54677
Name: count, dtype: int64

In [9]:
productos_df['productos_ean'].duplicated().sum()

np.int64(2276666)

In [10]:
# Verificamos que no haya un id_producto repetido como ean y como NO ean
mask = productos_df.groupby('id_producto')['productos_ean'].nunique() > 1

# Filtrar el DataFrame original con los valores que cumplen la condici√≥n
df_filtrado = productos_df[productos_df['id_producto'].isin(mask[mask].index)]
df_filtrado.head()

Empty DataFrame
Columns: [id_comercio, id_bandera, id_sucursal, id_producto, productos_ean, productos_descripcion, productos_cantidad_presentacion, productos_unidad_medida_presentacion, productos_marca, productos_precio_lista, productos_precio_referencia, productos_cantidad_referencia, productos_unidad_medida_referencia, productos_precio_unitario_promo1, productos_leyenda_promo1, productos_precio_unitario_promo2, productos_leyenda_promo2]
Index: []

In [11]:
columnas_de_interes = [ 
       'id_sucursal',
       'id_producto',
       'productos_ean',
       'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion',
       'productos_marca',
       'productos_precio_lista',
       'productos_precio_referencia',
       'productos_cantidad_referencia',
       'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1',
       'productos_leyenda_promo1',
       'productos_precio_unitario_promo2',
       'productos_leyenda_promo2'
]

In [12]:
productos_df = productos_df[columnas_de_interes]
productos_df.head()

,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,63.0,7.790771e+12,1.0,TOALLA NOSOTRAS CLASICAS C CALENDULA X 16U,1.0,UNI,NOSOTRAS,2709.0,169.31,16.0,UNI,NaN,NaN,NaN,NaN
1,711.0,7.790070e+12,1.0,FIDEOS DEDALITOS LUCCHETTI BOLSA X 500 GRS,1.0,UNI,LUCCHETTI,1439.0,2878.00,500.0,GRM,NaN,NaN,NaN,NaN
2,44.0,7.622202e+12,1.0,GALLETITAS BOCA DE DAMA TERRABUSI X 170 GRS,1.0,UNI,TERRABUSI,995.0,5852.94,170.0,GRM,NaN,NaN,NaN,NaN
3,62.0,7.791293e+12,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,3969.0,15876.00,250.0,CM3,NaN,NaN,NaN,NaN
4,2.0,7.791720e+12,1.0,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN

Dado nuestro an√°lisis previo de las sucursales, tomamos solamente las sucursales de la Ciudad Aut√≥noma de Buenos Aires y de la provincia de Buenos Aires. Ya que la mayor cantidad de sucursales del pa√≠s se concentran en estas jurisdicciones.

In [13]:
productos_df['dia_semana'] = dia_semana
productos_df['id_sucursal'] = productos_df['id_sucursal'].astype(int)
productos_df['productos_ean'] = productos_df['productos_ean'].astype(int).astype(bool)
# Convertir la columna 'id_producto' a categ√≥rica
productos_df['id_producto'] = productos_df['id_producto'].astype(int).astype(str).astype('category')
productos_df['productos_unidad_medida_presentacion'] = productos_df['productos_unidad_medida_presentacion'].astype('category')
productos_df['productos_marca'] = productos_df['productos_marca'].astype('category')
productos_df['productos_unidad_medida_referencia'] = productos_df['productos_unidad_medida_referencia'].astype('category')

# Mergear con sucursales
sucursales_df = pd.read_excel('sucursales_procesado.xlsx')
# Uno los dataframe por la columna de id_sucursal
productos_df = pd.merge(productos_df, sucursales_df, on='id_sucursal', how='inner')
display(productos_df.head())

# Ruta donde se guardar√° el zip
zip_filename = 'productos_procesado.zip'
csv_filename = 'productos_procesado.csv'

# Crear el archivo zip y guardar el CSV dentro
with zipfile.ZipFile(zip_filename, mode='w', compression=zipfile.ZIP_DEFLATED) as zf:
    with zf.open(csv_filename, mode='w') as f:
        productos_df.to_csv(f, sep='|', index=False)

,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2,dia_semana,id_bandera,sucursales_nombre,sucursales_tipo,sucursales_latitud,sucursales_longitud,sucursales_barrio,sucursales_localidad,sucursales_provincia
0,62,7791293050089,True,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,3969.0,15876.00,250.0,CM3,NaN,NaN,NaN,NaN,lunes,2,Champagnat,Hipermercado,-34.449813,-58.916319,NaN,Pilar,Buenos Aires
1,2,7791720018088,True,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN,lunes,1,Vicente L√≥pez,Hipermercado,-34.532302,-58.468176,NaN,Vicente L√≥pez,Buenos Aires
2,130,7798151952981,True,MANI TOSTADO CON CASCARA KING X 175 GRS,1.0,UNI,KING,1400.0,8000.00,175.0,GRM,NaN,NaN,NaN,NaN,lunes,2,Mar del Plata Centro,Supermercado,-37.998923,-57.553648,NaN,Mar del Plata,Buenos Aires
3,438,7791293045733,True,SHAMPOO CERAMIDAS SEDAL X 340 CC,1.0,UNI,SEDAL,4379.0,12879.41,340.0,CM3,NaN,NaN,NaN,NaN,lunes,3,25 de Mayo 2650,Supermercado,-34.500302,-58.694886,NaN,Los Polvorines,Buenos Aires
4,272,7790990999868,True,LAVAVAJILLA LIMON ZORRO BOTELLA X 500 CC,1.0,UNI,ZORRO,2209.0,4418.00,500.0,CM3,NaN,NaN,NaN,NaN,lunes,2,San Fernando II,Supermercado,-34.441795,-58.553738,NaN,San Fernando,Buenos Aires