In [2]:
pip install -r ../requirement.txt

Requirement already satisfied: pandas==2.2.3 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from -r ../requirement.txt (line 1)) (2.2.3)
Requirement already satisfied: openpyxl in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from -r ../requirement.txt (line 2)) (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from pandas==2.2.3->-r ../requirement.txt (line 1)) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from pandas==2.2.3->-r ../requirement.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from pandas==2.2.3->-r ../requirement.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from pandas==2.2.3->-r ../requirement.txt (line 1)) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from openpyxl->-r ../requirement.txt (line 2)) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\mbernardo\desktop\postgrado\aprendizaje de maquina\env\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r ../requirement.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
# pd.set_option('display.float_format', '{:.6f}'.format)
# Mostrar todas las columnas sin l√≠mite
pd.set_option('display.max_columns', None)

In [4]:
# Leer el archivo CSV
productos_df = pd.read_csv('productos.zip', sep='|')

productos_df.head()

C:\Users\mbernardo\AppData\Local\Temp\ipykernel_20336\2831869706.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  productos_df = pd.read_csv('productos.zip', sep='|')

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,10,1.0,63.0,7.790771e+12,1.0,TOALLA NOSOTRAS CLASICAS C CALENDULA X 16U,1.0,UNI,NOSOTRAS,2809.0,175.56,16.0,UNI,NaN,NaN,NaN,NaN
1,10,3.0,711.0,7.790070e+12,1.0,FIDEOS DEDALITOS LUCCHETTI BOLSA X 500 GRS,1.0,UNI,LUCCHETTI,1339.0,2678.00,500.0,GRM,NaN,NaN,NaN,NaN
2,10,1.0,44.0,7.622202e+12,1.0,GALLETITAS BOCA DE DAMA TERRABUSI X 170 GRS,1.0,UNI,TERRABUSI,959.0,5641.18,170.0,GRM,NaN,NaN,NaN,NaN
3,10,2.0,62.0,7.791293e+12,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,3969.0,15876.00,250.0,CM3,NaN,NaN,NaN,NaN
4,10,1.0,2.0,7.791720e+12,1.0,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN

In [5]:
productos_df.dtypes

id_comercio                              object
id_bandera                              float64
id_sucursal                             float64
id_producto                             float64
productos_ean                           float64
productos_descripcion                    object
productos_cantidad_presentacion         float64
productos_unidad_medida_presentacion     object
productos_marca                          object
productos_precio_lista                  float64
productos_precio_referencia             float64
productos_cantidad_referencia           float64
productos_unidad_medida_referencia       object
productos_precio_unitario_promo1        float64
productos_leyenda_promo1                 object
productos_precio_unitario_promo2        float64
productos_leyenda_promo2                float64
dtype: object

In [6]:
productos_df.describe()

,id_bandera,id_sucursal,id_producto,productos_ean,productos_cantidad_presentacion,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_precio_unitario_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
count,2.232853e+06,2.232853e+06,2.232853e+06,2.232853e+06,2232853.0,2.232853e+06,2.232853e+06,2.232853e+06,6.870200e+04,0.0,0.0
mean,2.065017e+00,3.166739e+02,7.322620e+12,9.777025e-01,1.0,1.050002e+04,2.112866e+04,3.965329e+02,6.686930e+04,NaN,NaN
std,8.728486e-01,2.318601e+02,1.653917e+12,1.476493e-01,0.0,8.212710e+04,9.270248e+04,5.130412e+02,2.463596e+05,NaN,NaN
min,1.000000e+00,1.000000e+00,4.008140e+07,0.000000e+00,1.0,3.600000e+01,2.700000e-01,0.000000e+00,4.500000e+01,NaN,NaN
25%,1.000000e+00,1.370000e+02,7.790315e+12,1.000000e+00,1.0,1.619000e+03,3.610000e+03,8.500000e+01,1.290000e+03,NaN,NaN
50%,2.000000e+00,2.560000e+02,7.791720e+12,1.000000e+00,1.0,2.790000e+03,8.350000e+03,2.370000e+02,1.990000e+03,NaN,NaN
75%,3.000000e+00,4.960000e+02,7.794521e+12,1.000000e+00,1.0,5.099000e+03,1.695000e+04,5.000000e+02,4.500000e+03,NaN,NaN
max,3.000000e+00,8.100000e+02,9.002490e+12,1.000000e+00,1.0,7.349000e+06,7.349000e+06,8.000000e+03,6.849000e+06,NaN,NaN

In [8]:
productos_df.tail()

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
2232849,10,2.0,512.0,2.509067e+12,0.0,QUESO CREMOSO FRACC SILVIA,1.0,KGM,S/D,14359.0,14359.0,1000.0,GRM,790.0,Promo A valida desde el 02/05/2025 hasta 04/05...,NaN,NaN
2232850,10,3.0,736.0,7.790010e+12,1.0,ACOND HIDRATACION INTENSA JOHNSONS KIDS X 200 CC,1.0,UNI,JOHNSONS BABY,4965.0,24825.0,200.0,CM3,2310.0,Promo A valida desde el 17/04/2025 hasta 20/05...,NaN,NaN
2232851,10,3.0,748.0,7.730908e+12,1.0,JUGO EN POLVO MIX FRUTAL RINDE DOS X 13GRS,1.0,UNI,RINDE DOS,559.0,4300.0,13.0,GRS,NaN,NaN,NaN,NaN
2232852,10,3.0,450.0,7.790070e+12,1.0,FIDEOS INTEGRALES SPAGHETTI MATARAZZO X 500 GRS,1.0,UNI,MATARAZZO,2009.0,4018.0,500.0,GRM,NaN,NaN,NaN,NaN
2232853,Ultima actualizaci√≥n: 2025-05-02T05:00:43-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#notamos que el ultimo registro de cada csv es irrelevante
productos_df = productos_df.drop(productos_df.index[-1])

In [10]:
productos_df.isnull().sum()

id_comercio                                   0
id_bandera                                    0
id_sucursal                                   0
id_producto                                   0
productos_ean                                 0
productos_descripcion                         0
productos_cantidad_presentacion               0
productos_unidad_medida_presentacion          0
productos_marca                               0
productos_precio_lista                        0
productos_precio_referencia                   0
productos_cantidad_referencia                 0
productos_unidad_medida_referencia            0
productos_precio_unitario_promo1        2164151
productos_leyenda_promo1                2164151
productos_precio_unitario_promo2        2232853
productos_leyenda_promo2                2232853
dtype: int64

In [11]:
len(productos_df)

2232853

In [12]:
productos_df.columns

Index(['id_comercio', 'id_bandera', 'id_sucursal', 'id_producto',
       'productos_ean', 'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion', 'productos_marca',
       'productos_precio_lista', 'productos_precio_referencia',
       'productos_cantidad_referencia', 'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1', 'productos_leyenda_promo1',
       'productos_precio_unitario_promo2', 'productos_leyenda_promo2'],
      dtype='object')

In [13]:
# verificamos cuantos registros tienen el codigo de producto EAN y cuantos no
productos_df['productos_ean'].value_counts()

productos_ean
1.0    2183066
0.0      49787
Name: count, dtype: int64

In [14]:

productos_df['productos_ean'].duplicated().sum()

np.int64(2232851)

In [15]:
#Verificamos que no haya un id_producto repetido como ean y como NO ean
mask = productos_df.groupby('id_producto')['productos_ean'].nunique() > 1

# Filtrar el DataFrame original con los valores que cumplen la condici√≥n
df_filtrado = productos_df[productos_df['id_producto'].isin(mask[mask].index)]
df_filtrado.head()

Empty DataFrame
Columns: [id_comercio, id_bandera, id_sucursal, id_producto, productos_ean, productos_descripcion, productos_cantidad_presentacion, productos_unidad_medida_presentacion, productos_marca, productos_precio_lista, productos_precio_referencia, productos_cantidad_referencia, productos_unidad_medida_referencia, productos_precio_unitario_promo1, productos_leyenda_promo1, productos_precio_unitario_promo2, productos_leyenda_promo2]
Index: []