In [1]:
pip install -r ../../requirements.txt

Requirement already satisfied: pandas==2.2.3 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: openpyxl in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 2)) (3.1.5)
Requirement already satisfied: matplotlib in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 3)) (3.10.3)
Requirement already satisfied: seaborn in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: scipy in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 5)) (1.15.3)
Requirement already satisfied: scikit-learn in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from -r ../../requirements.txt (line 6)) (1.6.1)
Requirement already satisfied: numpy>=1.23.2 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from pandas==2.2.3->-r ../../requirements.txt (line 1)) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from pandas==2.2.3->-r ../../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from pandas==2.2.3->-r ../../requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from pandas==2.2.3->-r ../../requirements.txt (line 1)) (2025.2)
Requirement already satisfied: et-xmlfile in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from openpyxl->-r ../../requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (25.0)
Requirement already satisfied: pillow>=8 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (3.2.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from scikit-learn->-r ../../requirements.txt (line 6)) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from scikit-learn->-r ../../requirements.txt (line 6)) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/alejandronicolastacchella/Documents/Personal/Maestría IA/AdD/ceia_add_tps/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r ../../requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import zipfile
# Mostrar todas las columnas sin límite
pd.set_option('display.max_columns', None)

In [3]:
dia_semana = 'sabado'
# Ruta al archivo zip
zip_path = f'{dia_semana}.zip'

# Abrir el zip
with zipfile.ZipFile(zip_path) as z:
    # Abrir solo el archivo CSV deseado
    with z.open('productos.csv') as f:
        productos_df = pd.read_csv(f, sep='|')

productos_df.head()

/var/folders/gf/xjt2z0l14fn8dy1y22cnhzm40000gn/T/ipykernel_24934/4000520671.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  productos_df = pd.read_csv(f, sep='|')

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,10,1.0,63.0,7.790771e+12,1.0,TOALLA NOSOTRAS CLASICAS C CALENDULA X 16U,1.0,UNI,NOSOTRAS,2709.0,169.31,16.0,UNI,NaN,NaN,NaN,NaN
1,10,3.0,744.0,7.799155e+12,1.0,AGUA MINERAL SIN GAS VILLAVICENCIO PET X 500 CC,1.0,UNI,VILLAVICENCIO,1459.0,2918.00,500.0,CM3,NaN,NaN,NaN,NaN
2,10,1.0,44.0,7.622202e+12,1.0,GALLETITAS BOCA DE DAMA TERRABUSI X 170 GRS,1.0,UNI,TERRABUSI,995.0,5852.94,170.0,GRM,NaN,NaN,NaN,NaN
3,10,2.0,62.0,7.791293e+12,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,4365.0,17460.00,250.0,CM3,NaN,NaN,NaN,NaN
4,10,1.0,2.0,7.791720e+12,1.0,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN

In [4]:
productos_df.tail()

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
2322436,10,3.0,442.0,7.798159e+12,1.0,SNACK PERROS GOLOCAN BOCADITOS CARNE CHOCO 100GRS,1.0,UNI,GOLOCAN,2025.0,2025.00,1.0,UNI,NaN,NaN,NaN,NaN
2322437,10,1.0,149.0,7.790896e+12,1.0,AGUA DE MESA SIN GAS BENEDICTINO PET X 1.5 LT,1.0,UNI,BENEDICTINO,1330.0,886.67,1500.0,CM3,NaN,NaN,NaN,NaN
2322438,10,3.0,669.0,7.791720e+12,1.0,CHOCLO CREMOSO AMARILLO CLASSIC LATA X 300 GRS,1.0,UNI,CARREFOUR CLASSIC,999.0,3330.00,300.0,GRM,NaN,NaN,NaN,NaN
2322439,10,3.0,441.0,7.794529e+12,1.0,TOSTADAS GRUESAS CLASICAS TOSTI X 200 GRS,1.0,UNI,TOSTI,1545.0,7725.00,200.0,GRM,NaN,NaN,NaN,NaN
2322440,Ultima actualización: 2025-05-24T04:59:09-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Notamos que el ultimo registro de cada csv es irrelevante
productos_df = productos_df.drop(productos_df.index[-1])

In [6]:
productos_df.isnull().sum()

id_comercio                                   0
id_bandera                                    0
id_sucursal                                   0
id_producto                                   0
productos_ean                                 0
productos_descripcion                         0
productos_cantidad_presentacion               0
productos_unidad_medida_presentacion          0
productos_marca                               0
productos_precio_lista                        0
productos_precio_referencia                   0
productos_cantidad_referencia                 0
productos_unidad_medida_referencia            0
productos_precio_unitario_promo1        2245952
productos_leyenda_promo1                2245952
productos_precio_unitario_promo2        2322440
productos_leyenda_promo2                2322440
dtype: int64

In [7]:
len(productos_df)

2322440

In [8]:
productos_df.columns

Index(['id_comercio', 'id_bandera', 'id_sucursal', 'id_producto',
       'productos_ean', 'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion', 'productos_marca',
       'productos_precio_lista', 'productos_precio_referencia',
       'productos_cantidad_referencia', 'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1', 'productos_leyenda_promo1',
       'productos_precio_unitario_promo2', 'productos_leyenda_promo2'],
      dtype='object')

In [9]:
# verificamos cuantos registros tienen el codigo de producto EAN y cuantos no
productos_df['productos_ean'].value_counts()

productos_ean
1.0    2267848
0.0      54592
Name: count, dtype: int64

In [10]:
productos_df['productos_ean'].duplicated().sum()

np.int64(2322438)

In [11]:
# Verificamos que no haya un id_producto repetido como ean y como NO ean
mask = productos_df.groupby('id_producto')['productos_ean'].nunique() > 1

# Filtrar el DataFrame original con los valores que cumplen la condición
df_filtrado = productos_df[productos_df['id_producto'].isin(mask[mask].index)]
df_filtrado.head()

Empty DataFrame
Columns: [id_comercio, id_bandera, id_sucursal, id_producto, productos_ean, productos_descripcion, productos_cantidad_presentacion, productos_unidad_medida_presentacion, productos_marca, productos_precio_lista, productos_precio_referencia, productos_cantidad_referencia, productos_unidad_medida_referencia, productos_precio_unitario_promo1, productos_leyenda_promo1, productos_precio_unitario_promo2, productos_leyenda_promo2]
Index: []

In [12]:
columnas_de_interes = [ 
       'id_sucursal',
       'id_producto',
       'productos_ean',
       'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion',
       'productos_marca',
       'productos_precio_lista',
       'productos_precio_referencia',
       'productos_cantidad_referencia',
       'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1',
       'productos_leyenda_promo1',
       'productos_precio_unitario_promo2',
       'productos_leyenda_promo2'
]

In [13]:
productos_df = productos_df[columnas_de_interes]
productos_df.head()

,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,63.0,7.790771e+12,1.0,TOALLA NOSOTRAS CLASICAS C CALENDULA X 16U,1.0,UNI,NOSOTRAS,2709.0,169.31,16.0,UNI,NaN,NaN,NaN,NaN
1,744.0,7.799155e+12,1.0,AGUA MINERAL SIN GAS VILLAVICENCIO PET X 500 CC,1.0,UNI,VILLAVICENCIO,1459.0,2918.00,500.0,CM3,NaN,NaN,NaN,NaN
2,44.0,7.622202e+12,1.0,GALLETITAS BOCA DE DAMA TERRABUSI X 170 GRS,1.0,UNI,TERRABUSI,995.0,5852.94,170.0,GRM,NaN,NaN,NaN,NaN
3,62.0,7.791293e+12,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,1.0,UNI,TRESEMME,4365.0,17460.00,250.0,CM3,NaN,NaN,NaN,NaN
4,2.0,7.791720e+12,1.0,ANANA EN RODAJAS BULNEZ LATA X 825 GRS,1.0,UNI,BULNEZ,2990.0,3624.24,825.0,GRM,NaN,NaN,NaN,NaN

Dado nuestro análisis previo de las sucursales, tomamos solamente las sucursales de la Ciudad Autónoma de Buenos Aires y de la provincia de Buenos Aires. Ya que la mayor cantidad de sucursales del país se concentran en estas jurisdicciones.

In [14]:
productos_df['dia_semana'] = dia_semana
productos_df['id_sucursal'] = productos_df['id_sucursal'].astype(int)
productos_df['productos_ean'] = productos_df['productos_ean'].astype(int).astype(bool)
# Convertir la columna 'id_producto' a categórica
productos_df['id_producto'] = productos_df['id_producto'].astype(int).astype(str).astype('category')
productos_df['productos_unidad_medida_presentacion'] = productos_df['productos_unidad_medida_presentacion'].astype('category')
productos_df['productos_marca'] = productos_df['productos_marca'].astype('category')
productos_df['productos_unidad_medida_referencia'] = productos_df['productos_unidad_medida_referencia'].astype('category')

# Mergear con sucursales
sucursales_df = pd.read_excel('sucursales_procesado.xlsx')
# Uno los dataframe por la columna de id_sucursal
productos_df = pd.merge(productos_df, sucursales_df, on='id_sucursal', how='left')
# Vamos a analizar las sucursales que son de la Ciudad Autónoma de Buenos Aires, de la provincia de Buenos Aires y del tipo supermercado
productos_df = productos_df[
    (productos_df['sucursales_provincia'] == 'Buenos Aires') | 
    (productos_df['sucursales_provincia'] == 'CABA')
]
productos_df = productos_df[productos_df['sucursales_tipo'] == 'Supermercado']
display(productos_df.head())

# Ruta donde se guardará el zip
zip_filename = 'productos_procesado.zip'
csv_filename = 'productos_procesado.csv'

# Crear el archivo zip y guardar el CSV dentro
with zipfile.ZipFile(zip_filename, mode='w', compression=zipfile.ZIP_DEFLATED) as zf:
    with zf.open(csv_filename, mode='w') as f:
        productos_df.to_csv(f, sep='|', index=False)

,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2,dia_semana,id_bandera,sucursales_nombre,sucursales_tipo,sucursales_latitud,sucursales_longitud,sucursales_barrio,sucursales_localidad,sucursales_provincia
5,130,7798151952981,True,MANI TOSTADO CON CASCARA KING X 175 GRS,1.0,UNI,KING,1300.0,7428.57,175.0,GRM,NaN,NaN,NaN,NaN,sabado,2,Mar del Plata Centro,Supermercado,-37.998923,-57.553648,NaN,Mar del Plata,Buenos Aires
6,438,7791293045733,True,SHAMPOO CERAMIDAS SEDAL X 340 CC,1.0,UNI,SEDAL,4419.0,12997.06,340.0,CM3,NaN,NaN,NaN,NaN,sabado,3,25 de Mayo 2650,Supermercado,-34.500302,-58.694886,NaN,Los Polvorines,Buenos Aires
9,272,7790990999868,True,LAVAVAJILLA LIMON ZORRO BOTELLA X 500 CC,1.0,UNI,ZORRO,2209.0,4418.00,500.0,CM3,NaN,NaN,NaN,NaN,sabado,2,San Fernando II,Supermercado,-34.441795,-58.553738,NaN,San Fernando,Buenos Aires
10,120,7790040173200,True,GALLETITAS KESITAS ESTUCHE X 125 GRS,1.0,UNI,KESITAS,1769.0,14152.00,125.0,GRM,NaN,NaN,NaN,NaN,sabado,2,Belgrano Cabildo,Supermercado,-34.558821,-58.459349,NaN,Ciudad Autónoma de Buenos Aires,CABA
19,212,7791720039748,True,GALLETITAS SURTIDO RELLENAS BULNEZ X 350 GRS,1.0,UNI,BULNEZ,1550.0,4428.57,350.0,GRM,NaN,NaN,NaN,NaN,sabado,2,Malaver - Villa Ballester,Supermercado,-34.557290,-58.550437,NaN,Villa Ballester,Buenos Aires